name: graphql

include:
  - path: ./server/compose.yml
  - path: ./docker/database/compose.yml

services:
  elysia:
    build:
      target: production
    container_name: elysia-prod

volumes:
  graphql-data:
    driver: local
    name: graphql-data

networks:
  graphql-network:
    driver: bridge
    name: graphql-network
