services:
  migrations:
    # Do not restart the migrations container
    restart: "no"
    entrypoint: ["bunx", "--bun", "prisma", "migrate", "deploy"]
    depends_on:
      # Wait for the database to be healthy
      postgres:
        condition: service_healthy
    networks:
     - stocky-network
