services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - stocky-network
    volumes:
      - stocky-data:/var/lib/postgresql/data
    healthcheck:
      # Use pg_isready to check if the database is ready
      test: ["CMD-SHELL", "pg_isready -U stocky -d stocky"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - "5432:5432"
